var MarkdownEditorModel = Backbone.View.extend({
    savePostOnServer:function(data,success,fail){
        $.ajax({
            url:'/uploadPost',
            data:{
                title:data.title,
                text:data.text,
                type:data.type
            },
            type:'POST',
            dataType:'text'
        }).done(function(res){
                if(res=='success'){
                    if(success){
                        success(res);
                    }
                }else{
                    if(fail){
                        fail(res);
                    }
                }
            }).fail(function(){
                if(fail) fail('Request failed!');
            });
    },
    getLastFile:function(callback){
        $.ajax({
            url:'/MarkdownEditor/getLastFile',
            type:'GET',
            dataType:'text',
            async:false
        }).done(function(res){
            callback(res);
        }).fail(function(){
            console.log('请检查网络连接');
        });
    },
    saveTempFile:function(text){
        // console.log(text);
        $.ajax({
            url:'/MarkdownEditor/saveTempFile',
            type:'POST',
            dataType:'text',
            data:{
                data:text
            }
        }).done(function(res){
            if(res!=='success'){
                console.log(res);
            }
        }).fail(function(){
            console.log('Temp file saving link error.');
        });
    }
});